services:
  db:
    image: postgres:16
    container_name: estate_dev_db
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estate_dev_web
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -lc "tail -f /dev/null"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"   # оставим на будущее
    restart: unless-stopped
