name: Deploy to lokipaw.com

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: deploy-main
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}      # lokipaw.com
      SSH_PORT: ${{ secrets.SSH_PORT }}      # 22022
      SSH_USER: ${{ secrets.SSH_USER }}      # feda
      DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}  # /home/feda/docker/estate_master
    steps:
      - uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Make sure target dir exists
        run: ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "mkdir -p '$DEPLOY_DIR'"

      - name: Rsync sources to server (keep .env files)
        env:
          RSYNC_EXCLUDES: "--exclude .git/ --exclude pgdata/ --exclude media/ --exclude staticfiles/ --exclude .env --exclude .env.*"
        run: |
          rsync -az --delete $RSYNC_EXCLUDES \
            -e "ssh -p $SSH_PORT -o StrictHostKeyChecking=no" \
            ./ "$SSH_USER@$SSH_HOST:$DEPLOY_DIR/"

      - name: Rebuild & restart with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" '
            set -euxo pipefail
            cd "$DEPLOY_DIR"

            # если вдруг строка env_file: .env осталась в compose — уберём
            sed -i "/^ *env_file: *.env$/d" docker-compose.yml || true

            # .env.prod должен быть на сервере (мы его больше не удаляем rsync-ом)
            [ -f .env.prod ] || { echo "::error::.env.prod missing in $DEPLOY_DIR"; exit 1; }

            docker compose --env-file .env.prod down || true
            docker compose --env-file .env.prod up -d --build
            docker compose --env-file .env.prod ps
          '
