name: Deploy to lokipaw.com

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ssh-agent
        uses: actions/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}   # твой приватный ключ

      - name: Trust lokipaw.com host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H lokipaw.com >> ~/.ssh/known_hosts

      - name: Rsync project to server
        env:
          RSYNC_EXCLUDES: "--exclude .git/ --exclude pgdata/ --exclude media/ --exclude staticfiles/"
        run: |
          set -eux
          # <<< ВАЖНО: укажи ПРАВИЛЬНЫЙ путь на сервере >>>
          RSYNC_DEST="feda@lokipaw.com:/home/feda/docker/estate_master/"
          rsync -az --delete $RSYNC_EXCLUDES ./ "$RSYNC_DEST"

      - name: Rebuild & restart on server
        run: |
          set -eux
          ssh feda@lokipaw.com '
            cd ~/docker/estate_master &&
            docker compose down &&
            docker compose up -d --build
          '
