name: Deploy to lokipaw.com

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

# чтобы не стартовало несколько деплоев параллельно
concurrency:
  group: deploy-main
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-24.04

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}        # lokipaw.com
      SSH_PORT: ${{ secrets.SSH_PORT }}        # 22022
      SSH_USER: ${{ secrets.SSH_USER }}        # feda
      DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}    # /home/feda/docker/estate_master

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rsync (just in case)
        run: sudo apt-get update -y && sudo apt-get install -y rsync

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}   # ПРИВАТНЫЙ ключ с Mac (~/.ssh/estate_ci_key)

      - name: Add server host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Rsync sources to server (force publickey, verbose)
        run: |
          set -euo pipefail
          RSYNC_EXCLUDES="--exclude .git/ --exclude pgdata/ --exclude media/ --exclude staticfiles/"
          SSH_OPTS="-p $SSH_PORT -o PreferredAuthentications=publickey -o PubkeyAuthentication=yes -o StrictHostKeyChecking=accept-new -vvv"
          rsync -az $RSYNC_EXCLUDES -e "ssh $SSH_OPTS" ./ "$SSH_USER@$SSH_HOST:$DEPLOY_DIR/"

      - name: Build & restart on server
        run: |
          SSH_OPTS="-p $SSH_PORT -o PreferredAuthentications=publickey -o PubkeyAuthentication=yes -o StrictHostKeyChecking=accept-new -vvv"
          ssh $SSH_OPTS "$SSH_USER@$SSH_HOST" bash -lc '
            cd "$DEPLOY_DIR"
            ln -sf .env.prod .env || true
            docker compose down
            docker compose up -d --build
            docker system prune -f
          '

      - name: Smoke-check (curl)
        run: |
          # Проверим, что контейнер отдаёт 200/HTML
          curl -I http://$SSH_HOST:8000/ || true
