- name: Start ssh-agent and add key
  uses: webfactory/ssh-agent@v0.9.0
  with:
    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

- name: Rsync sources to server
  run: |
    RSYNC_EXCLUDES="--exclude .git/ --exclude pgdata/ --exclude media/ --exclude staticfiles/"
    rsync -az -e "ssh -p ${{ secrets.SSH_PORT }}" $RSYNC_EXCLUDES ./ \
      ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_DIR }}
